// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/proto/checker.proto

package checker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VulnerabilityChecker_CheckConfig_FullMethodName = "/checker.VulnerabilityChecker/CheckConfig"
)

// VulnerabilityCheckerClient is the client API for VulnerabilityChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VulnerabilityCheckerClient interface {
	CheckConfig(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type vulnerabilityCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewVulnerabilityCheckerClient(cc grpc.ClientConnInterface) VulnerabilityCheckerClient {
	return &vulnerabilityCheckerClient{cc}
}

func (c *vulnerabilityCheckerClient) CheckConfig(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, VulnerabilityChecker_CheckConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VulnerabilityCheckerServer is the server API for VulnerabilityChecker service.
// All implementations must embed UnimplementedVulnerabilityCheckerServer
// for forward compatibility.
type VulnerabilityCheckerServer interface {
	CheckConfig(context.Context, *CheckRequest) (*CheckResponse, error)
	mustEmbedUnimplementedVulnerabilityCheckerServer()
}

// UnimplementedVulnerabilityCheckerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVulnerabilityCheckerServer struct{}

func (UnimplementedVulnerabilityCheckerServer) CheckConfig(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckConfig not implemented")
}
func (UnimplementedVulnerabilityCheckerServer) mustEmbedUnimplementedVulnerabilityCheckerServer() {}
func (UnimplementedVulnerabilityCheckerServer) testEmbeddedByValue()                              {}

// UnsafeVulnerabilityCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VulnerabilityCheckerServer will
// result in compilation errors.
type UnsafeVulnerabilityCheckerServer interface {
	mustEmbedUnimplementedVulnerabilityCheckerServer()
}

func RegisterVulnerabilityCheckerServer(s grpc.ServiceRegistrar, srv VulnerabilityCheckerServer) {
	// If the following call panics, it indicates UnimplementedVulnerabilityCheckerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VulnerabilityChecker_ServiceDesc, srv)
}

func _VulnerabilityChecker_CheckConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VulnerabilityCheckerServer).CheckConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VulnerabilityChecker_CheckConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VulnerabilityCheckerServer).CheckConfig(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VulnerabilityChecker_ServiceDesc is the grpc.ServiceDesc for VulnerabilityChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VulnerabilityChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "checker.VulnerabilityChecker",
	HandlerType: (*VulnerabilityCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckConfig",
			Handler:    _VulnerabilityChecker_CheckConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/checker.proto",
}
