// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/checker.proto

package checker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_api_proto_checker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_checker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_checker_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CheckResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Vulnerabilities []*Vulnerability       `protobuf:"bytes,1,rep,name=vulnerabilities,proto3" json:"vulnerabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_api_proto_checker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_checker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_checker_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetVulnerabilities() []*Vulnerability {
	if x != nil {
		return x.Vulnerabilities
	}
	return nil
}

type Vulnerability struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Level          string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Recommendation string                 `protobuf:"bytes,2,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Vulnerability) Reset() {
	*x = Vulnerability{}
	mi := &file_api_proto_checker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vulnerability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vulnerability) ProtoMessage() {}

func (x *Vulnerability) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_checker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vulnerability.ProtoReflect.Descriptor instead.
func (*Vulnerability) Descriptor() ([]byte, []int) {
	return file_api_proto_checker_proto_rawDescGZIP(), []int{2}
}

func (x *Vulnerability) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Vulnerability) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

var File_api_proto_checker_proto protoreflect.FileDescriptor

const file_api_proto_checker_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/checker.proto\x12\achecker\"\"\n" +
	"\fCheckRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"Q\n" +
	"\rCheckResponse\x12@\n" +
	"\x0fvulnerabilities\x18\x01 \x03(\v2\x16.checker.VulnerabilityR\x0fvulnerabilities\"M\n" +
	"\rVulnerability\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12&\n" +
	"\x0erecommendation\x18\x02 \x01(\tR\x0erecommendation2T\n" +
	"\x14VulnerabilityChecker\x12<\n" +
	"\vCheckConfig\x12\x15.checker.CheckRequest\x1a\x16.checker.CheckResponseB\x13Z\x11api/proto/checkerb\x06proto3"

var (
	file_api_proto_checker_proto_rawDescOnce sync.Once
	file_api_proto_checker_proto_rawDescData []byte
)

func file_api_proto_checker_proto_rawDescGZIP() []byte {
	file_api_proto_checker_proto_rawDescOnce.Do(func() {
		file_api_proto_checker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_checker_proto_rawDesc), len(file_api_proto_checker_proto_rawDesc)))
	})
	return file_api_proto_checker_proto_rawDescData
}

var file_api_proto_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_checker_proto_goTypes = []any{
	(*CheckRequest)(nil),  // 0: checker.CheckRequest
	(*CheckResponse)(nil), // 1: checker.CheckResponse
	(*Vulnerability)(nil), // 2: checker.Vulnerability
}
var file_api_proto_checker_proto_depIdxs = []int32{
	2, // 0: checker.CheckResponse.vulnerabilities:type_name -> checker.Vulnerability
	0, // 1: checker.VulnerabilityChecker.CheckConfig:input_type -> checker.CheckRequest
	1, // 2: checker.VulnerabilityChecker.CheckConfig:output_type -> checker.CheckResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_checker_proto_init() }
func file_api_proto_checker_proto_init() {
	if File_api_proto_checker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_checker_proto_rawDesc), len(file_api_proto_checker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_checker_proto_goTypes,
		DependencyIndexes: file_api_proto_checker_proto_depIdxs,
		MessageInfos:      file_api_proto_checker_proto_msgTypes,
	}.Build()
	File_api_proto_checker_proto = out.File
	file_api_proto_checker_proto_goTypes = nil
	file_api_proto_checker_proto_depIdxs = nil
}
